### ISSUE TITLE
Renders too wide on mobile.

### ISSUE THREAD

**Issue by coder13** [saranshgrover/WCARealTime#4]
This doesn't happen on the main page, but on the comp info pages.

It seems like the content renders too wide. There's a horizontal scrollbar and the menubar isn't the length of the page.

Tested on chrome for android.

**Comment by saranshgrover** [comment]
I fixed this in the [refactor branch code](https://github.com/saranshgrover/myComp/tree/refactor) so I'm closing this. Still need to do a lot of work before it gets merged though.
